### ISSUE TITLE
Topics filter includes options omitted on the event's card

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#111]
Pre-requisites:
Create an event that has more than 4 topics (say 6 total topics)

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the left side-filters panel, invoke the topics filter

Expected Result:
Since only first 4 topics specified on the md file are displayed on the event card/tile - the 5th and 6th topics should not be displayed on the Topics filter as well

Actual Result:
The 5th and 6th topics are displayed on the Topics filter.

**Comment by Thangaraj-Ideas2it** [comment]
Topics dropdown updated to show only topics shown in UI @WinsCodes  Please verify

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
