### ISSUE TITLE
Tool tip displayed when hovering on selected locations on location-filter is not understandable

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#112]
Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the left side-filters panel, invoke the location filter and select multiple locations
3. Hover over the count-label displayed on the location combo box

Observation:
The tool tip displaying all the selected locations is not understandable - please refer the snapshot attached.

Snapshot:
<img width="441" alt="multiple location-tool tip issue" src="https://user-images.githubusercontent.com/120092872/222205499-e02270eb-443e-4e97-ab58-fb14a9703237.png">

**Comment by Thangaraj-Ideas2it** [comment]
Replaced comma with pipe symbol.. Please verify @WinsCodes
