### ISSUE TITLE
Clicking 'Clear All' after searching a filter with an unavailable option makes all the filter's options disappear

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#113]
Priority/Severity: High/High

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the left-side filters panel say 'Location' filter, click on the combo box's search area and type any unavailable filter-option
3. Click somewhere outside the combo box
4. Click the 'Clear All' hyperlink

Expected result:
The location combo box should be reset and all its options should be displayed when invoked.

Actual result:
The location combo box gets reset but all its options disappear - please refer the snapshot attached

Snapshot:
<img width="200" alt="Filter options disappear issue" src="https://user-images.githubusercontent.com/120092872/222207575-bc7a6ea6-59fd-45b4-9dc0-659989242752.png">

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the above issue. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is resolved now.
