### ISSUE TITLE
Blank-empty logos displayed for filter options

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#116]
Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the left-side filters panel invoke any filter say the 'Year' filter

Observation:
Blank-empty logos displayed for all filter options - please refer the snapshot attached.

Snapshot:
<img width="194" alt="Filters-blank empty logos SS" src="https://user-images.githubusercontent.com/120092872/222210221-b10f480e-02dd-4121-ad56-103c3cfef717.png">

**Comment by Thangaraj-Ideas2it** [comment]
removed the empty image placeholders. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is resolved now.
