### ISSUE TITLE
Host names not displayed as a tool tip when user hovers over the respective host-logos

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#118]
Pre-requisite:
Create an event with multiple host names and their respective host logos

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed (on the related event card/tile) hover over the host logos displayed

Expected Result:
The host names should be displayed as a tool tip

Actual Result:
The host names are be displayed as a tool tip

**Comment by Thangaraj-Ideas2it** [comment]
Added tool tip for hostnames. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
