### ISSUE TITLE
Same host name from different events get repeated/duplicated multiple times on the 'Event Hosts' filter

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#119]
Pre-requisite:
Create 2 events with same host names

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel, invoke the Event hosts filter

Expected Result:
The host names should not get duplicated and should be displayed as distinct-unique options.

Actual Result:
Same host names get repeated/duplicated and are displayed multiple times - please refer the snapshot attached.

Snapshot:
<img width="196" alt="Repeated duplicate host names issue SS" src="https://user-images.githubusercontent.com/120092872/222213419-21d3f87d-a2c7-4e2a-b562-9d3a5658d738.png">

**Comment by Thangaraj-Ideas2it** [comment]
Fixed issue to show uniques hostnames.. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
