### ISSUE TITLE
Event Hosts filter's options not displayed in sorted alphabetical order

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#121]
Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel, invoke the 'Event Hosts' filter

Expected Result:
The filter-options should get displayed in sorted alphabetic order.

Actual Result:
The filter-options are not displayed in sorted alphabetic order - please refer the snapshot attached.

Snapshot:
<img width="177" alt="HostNames filter-options unsorted issue SS" src="https://user-images.githubusercontent.com/120092872/222216475-ff3960b3-8648-4e64-82f1-398c4f745955.png">

**Comment by Thangaraj-Ideas2it** [comment]
Fixed issue.. to show list in alphabetical order. please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
