### ISSUE TITLE
Topics filter's options not displayed in sorted alphabetical order

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#122]
Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel, invoke the 'Topics' filter

Expected Result:
The filter-options should get displayed in sorted alphabetic order.

Actual Result:
The filter-options are not displayed in sorted alphabetic order - please refer the snapshot attached.

Snapshot:
<img width="187" alt="Topic filter-options unsorted issue SS" src="https://user-images.githubusercontent.com/120092872/222216812-026f0c38-b16b-452e-a72a-2dcadfbbcf85.png">

**Comment by Thangaraj-Ideas2it** [comment]
Fixed issue.. to show list in alphabetical order.. please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
