### ISSUE TITLE
Events_Mobile-'No matching events available' label not displayed when user applies the related filter changes

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#124]
Steps to reproduce:

1. On the mobile browser, launch the Application Under Test url: https://events-qa.on.fleek.co/
2. Click on the 'Filters' button and invoke the filters panel
3. Make some changes on the filters (that have no events to display) and click on the 'View' button displayed at the bottom to apply the changes made.

Expected Result:
'No matching events available' label should get displayed when user applies the related filter changes

Actual Result:
'No matching events available' label does not gets displayed (user has to scroll a bit to make the label appear)

**Comment by Thangaraj-Ideas2it** [comment]
Modified the code to show the message without scroll. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
