### ISSUE TITLE
Schedule filter-Unable to set range for a single day to view all events on the day

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#132]
Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel, invoke the 'Schedule' filter and try setting the start and end dates to a single day (trying to view all events on the required day).

Expected Result:
User should be able to set the schedule and related events should be displayed on the timeline.

Actual Result:
User unable to schedule for a single day.

**Comment by Thangaraj-Ideas2it** [comment]
Fixed issue to select a single date in date range. please verify @WinsCodes
