### ISSUE TITLE
Longer topic names don't get correctly placed when selected on the filter

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#133]
Pre-requisite:
Create an event with the topic attribute set to a longer value.

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel, invoke the 'Topics' filter and select the longer-topic (mentioned in the pre-requisite).

Expected Result:
The selected topic should be displayed properly without any placement issues.

Actual Result:
The selected topic is not displayed to be properly placed - please refer the snapshot attached.

Snapshot:
![longer Topic names on filter issue](https://user-images.githubusercontent.com/120092872/222637063-fa7b1031-c320-4df0-b579-c70e75a4af0a.jpg)

**Comment by Thangaraj-Ideas2it** [comment]
Added support to display long texts. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
