### ISSUE TITLE
User selecting End date lesser than the Start date (already selected) resets the 'End Date' field back to 31 Dec

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#134]
Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel, invoke the 'Start date' on the Schedule filter and set any date (say '7 Jan')
3. Now invoke the 'End date' on the Schedule filter and try setting the date as '5 Jan'

Expected Result:
'5 Jan' should get selected as the End date

Actual Result:
The End date gets reset to 31 Dec (since the selected date was less than the Start date already selected).

Note:
- The issue is common for both the other way as well - User selecting Start date greater than the End date (already selected) resets the 'Start Date' field back to 1 Jan
- Can be made that when either of the dates (Start/End) does not serve as a valid combination to the date currently being selected-the other field can be made blank or so-thus informing the user that since he selected a date and other date is not a valid date range now-he/she needs to set the other date as well.

**Comment by Thangaraj-Ideas2it** [comment]
Modified the logic to show dates as disabled  beyond the selected  date range. User has to manually extended the range to avoid the above mentioned issue. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
