### ISSUE TITLE
'Jump to month' feature - Previous month shown when the user is on January month

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#135]
Pre-requisites:
Create an event that falls on the January month.

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed, go to the event displayed on the month of January.
3. Click on the 'January' label to invoke the 'Jump to month' feature

Expected Result:
'Previous month' option should be disabled (stating that the user cannot go to the previous month since he is already on January - the first month of the year)

Actual Result:
'Previous month' option is displayed as enabled - please refer the snapshot attached.

Snapshot:
![Previous month on January](https://user-images.githubusercontent.com/120092872/222639505-4589d8f6-d2a5-4c15-a91e-8dbc91edd740.jpg)

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the above. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
