### ISSUE TITLE
'Jump to Feature' feature - Specific month's sub-options remain displayed even when user clicks outside

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#137]
Pre-requisites:
Create multiple event that falls on different months

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed, go to the event displayed on any month and click on the month's label (invoking the 'Jump to month' feature)
3. Click the 'Specific Month' option to display the sub-options (the various months)

Expected Result:
The specific month's options should get dismissed when user clicks outside.

Actual Result:
The specific month's options remain displayed even when user clicks outside - please refer the snapshot attached.

Snapshot:
![Specific month options stay when user clicks outside](https://user-images.githubusercontent.com/120092872/222641102-086f1054-b80f-4549-8920-0ff9c26aa512.JPG)

**Comment by Thangaraj-Ideas2it** [comment]
Fixed above issue.. please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
