### ISSUE TITLE
'Jump to month' feature - 'Next month' options remains enabled even when no events present in the rest of the year

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#139]
Pre-requisites:
Create a single event that falls on January month

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed, go to the event displayed and click on the month's label (invoking the 'Jump to month' feature)

Expected Result:
'Next month' option should be displayed as disabled (since no events present on the rest of the year)

Actual Result:
'Next month' option displayed as enabled even when no events for the rest of the year

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the above issue. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
