### ISSUE TITLE
Archived events not getting displayed on the timeline

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#140]
Pre-requisites:
- Create an event that falls on the previous year (eg.) 2022

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel, invoke the 'Year' filter and select the year 2022

Expected result:
The archived events (falling in the year 2022) should get successfully displayed on the timeline.

Actual result:
The archived events are not getting displayed on the timeline.

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the issue. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
