### ISSUE TITLE
Filters - Events not displayed when schedule filter is set based on the event's end date or in between dates

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#143]
Pre-requisites:
Create an event that spans for a couple of days (say 1 Jan - 7 Jan)

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel invoke the Schedule filter-Start date and select the date as '3 Jan'

Expected Result:
The related event (created on the pre-requisite) should get successfully displayed

Actual Result:
The related event (created on the pre-requisite) does not gets displayed.

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the issue to show events between date range.. @WinsCodes  Please verify

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
