### ISSUE TITLE
Clicking on the area before the 1st of any month gives 'Application error'

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#144]
Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel invoke the Schedule filter-Start date and click on any area before the 1st of the month

Expected Result:
No issues/errors should get displayed

Actual Result:
Application error gets displayed - please refer the snapshot attached.

Snapshot:
![Clicking on ares before 1st of the month-App error SS](https://user-images.githubusercontent.com/120092872/222644688-6cdacdcc-39d7-4f5e-b14a-4b12a3aa6a62.JPG)

**Comment by Thangaraj-Ideas2it** [comment]
Handled the error scenario. @WinsCodes  Please verify

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
