### ISSUE TITLE
Events_Mobile-'Jump to month' feature missing on mobile

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#146]
Pre-requisite:
Create an event with valid required details

Steps to reproduce:

1. On the mobile browser, launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed, go to the event displayed and click on the month label to invoke the 'Jump to month' feature.

Expected result:
The user should be able to use the 'Jump to month' feature.

Actual result:
The 'Jump to month' feature is missing

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the issue. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
