### ISSUE TITLE
Events not displayed when Schedule filter's  start date is set as the event's end date

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#150]
Pre-requisite:
Create an event that spans for a couple of days (say December 24 - 25, 2023)

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel invoke the Schedule filter-Start date and select the date as '25 Dec'

Expected Result:
The related event should get successfully displayed.

Actual Result:
The related event is not getting displayed

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the issue. please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
