### ISSUE TITLE
Preferred contacts-icons when hovered over does not display the related name in tool tip

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#153]
Pre-requisite:
Create an event that has the preferred contacts properly setup (such as facebook, instagram, whatsapp or even any other means of contact)

Steps to reproduce:

1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed, go to the event (created in the pre-requisite)
3. Using the mouse, hover over the preferred contact-icon

Observation:
The related preferred contact is not displayed as a tool tip.

**Comment by Thangaraj-Ideas2it** [comment]
Added support for tool tip. @WinsCodes please verify

**Comment by WinsCodes** [comment]
Verified that the issue is resolved now.
