### ISSUE TITLE
Show past events separately 

### ISSUE THREAD

**Issue by pandeyanujk** [memser-spaceport/pln-events#17]
eta: 2023-02
As an event consumer, when I go to the event's webpage, I need to clearly see events that are no longer active/current, so that I can focus on active & future events. 

- Improve the UI to signify past events clearly. 
- Ability to collapse or move past events/months from the main page/view. 

eta: 2023-02

**Comment by abarna-visvanathan** [comment]
This issue is delivered on 24th Feb,2023
