### ISSUE TITLE
Add PL logo to the events page window/tab title

### ISSUE THREAD

**Issue by pandeyanujk** [memser-spaceport/pln-events#18]
- The logo/icon for the events calendar page is blank. Add the PL logo there similar to the directory. 
<img width="366" alt="image" src="https://user-images.githubusercontent.com/25129657/215391878-228796c5-da8b-4a0a-8149-4a8ab2f4c0e3.png">

eta: 2023-02

**Comment by abarna-visvanathan** [comment]
This issue is delivered on 24th Feb,2023
