### ISSUE TITLE
The Calendar does not refresh when a different year is selected (archived/future)

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#215]
T500: Verifying the Calendar view for past events (current year)
https://memser.testrail.io/index.php?/tests/view/500
                        
Steps to reproduce:
1. Launch the AUT url: https://events-qa.on.fleek.co/
2. Click on the Calendar icon on the view panel
3. Once the Calendar view is displayed, from the filters panel-select an archived/future year.

Expected Result:
- The Calendar should get refreshed displaying the related events of the year
- The 1st event of the year should automatically get displayed

Actual Result:
- The Calendar does not gets refreshed displaying the related events of the year
- The Calendar does not gets refreshed and remains on the same month

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the above issue. @WinsCodes  Please verify

**Comment by WinsCodes** [comment]
Verified and found the issue resolved (build tested: QA Build 004)
