### ISSUE TITLE
Events_Mobile - View panel displayed inside the Filters panel

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#223]
Steps to reproduce:

1. Launch the PLN Events page
2. Click the Filters button to invoke the Filters panel

Observation:
The view panel is displayed inside the filters panel - please find the snapshot attached

Snapshot:
![View panel displayed inside the Filters panel](https://user-images.githubusercontent.com/120092872/224989709-fa7d8070-6bbb-4172-9d08-984de3a8355f.jpg)

**Comment by Thangaraj-Ideas2it** [comment]
Removed the view panel in mobile. @WinsCodes  please verify
