### ISSUE TITLE
Expected logos for a single day event are not displayed

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#227]
T549: Verifying the Calendar view for a single day event to display Host Logo, Event Type Logo, PLN Event/Industry event  logo and the Event Name
https://memser.testrail.io/index.php?/tests/view/549
                        
Expected:
Single day event should display all expected logos

Actual:
Single day event does not display all expected logos - please refer the snapshot attached
![mobile-single day no logos displayed issue](https://user-images.githubusercontent.com/120092872/225000360-4eadf6db-bb91-4420-a17c-a576e067093b.jpg)

**Comment by Thangaraj-Ideas2it** [comment]
@WinsCodes  For mobile the UX doesn't include the logos and there wont be space too. So this can be closed
