### ISSUE TITLE
Events-Launching event card and dismissing the same resets the Calendar's view (scrolled position)

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#242]
Pre-requisite:
Create events at the last week of a month (so that the user will require to scroll the Calendar view down to click and launch the event card)

Steps to reproduce:
1. Launch PLN Events page
2. Using the View panel, switch to the Calendar view
3. Scroll down to the event and click on it to launch the event card (dismiss it by clicking the 'X' button on the card)

Expected Result:
The event card is launched and the Calendar view displays the related event (the card was launched from) - dismissing it the Calendar should remain on the same row the card was launched from.

Actual Result:
The event card is launched but the Calendar view is reset to the page's top on dismissing the event card.

Note: The issue is observed on mobile browser as well.

**Comment by Thangaraj-Ideas2it** [comment]
Issue is fixed. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified the defect to be resolved - hence closing the issue.
