### ISSUE TITLE
'Clear All' resets the 'Year'-combo box's default option to 'All' but not the current year

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#72]
Priority/Severity: High/High

Pre-requisites:
Create events that fall in previous year (apart from the current year)

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the filters panel (displayed on page's left side) - set the 'Year' filter to a different year (any year other than the current year-2023)
3. Click the 'Clear All' hyperlink (displayed on the top-right of Filters panel)

Expected result:
Clicking 'Clear All' should reset the Year combo box to the current year (i.e) 2023

Actual result:
Clicking the 'Clear All' resets the Year combo box to the option 'All'

**Comment by abarna-visvanathan** [comment]
This issue is fixed and delivered on 24th Feb,2023
