### ISSUE TITLE
Start and end dates still displayed when the attribute: dateTBD is set as 'true'

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#73]
Priority/Severity: High/High

Pre-requisites:
Create an event that has the following - 
1. startDate: 02/23/2023
2. endDate: 02/24/2023
3. dateTBD: true

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed, verify the event's date field

Expected result:
The date should be displayed as 'Date TBD'

Actual result:
The Start and end dates are displayed (such as February 23 - 24, 2023)

**Comment by abarna-visvanathan** [comment]
This issue is fixed and delivered on 24th Feb,2023
