### ISSUE TITLE
Event's location field not displayed as a hyperlink (when the venue map link detail is available)

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#75]
Priority/Severity: Medium/Medium

Pre-requisites:
Create an event that has its location and venueMapsLink attributes specified as follows: 
location: Boston, United States
venueMapsLink: "https://goo.gl/maps/esRVcTLd6nK2L26a7"

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline, verify the event's location field displayed

Expected result:
The location field should be displayed as a hyperlink (since the attribute: 'venueMapsLink' has been provided)

Actual result:
The location field is not displayed as a hyperlink

**Comment by abarna-visvanathan** [comment]
This issue is fixed and delivered on 24th Feb,2023
