### ISSUE TITLE
Clicking 'Clear All' after searching a filter with an unavailable option makes all the options other than 'All' disappear

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#77]
Priority/Severity: High/High

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the left-side filters panel say 'Location' filter, click on the combo box's search area and search for any unavailable option
3. Click somewhere outside the combo box
4. Click the 'Clear All' hyperlink

Expected result:
The location combo box should be reset to its default option 'All' (and all other options should also be displayed when invoked)

Actual result:
The location combo box gets reset to its default option 'All' (BUT all other options disappear)

**Comment by abarna-visvanathan** [comment]
This issue is fixed and delivered on 24th Feb,2023
