### ISSUE TITLE
Longer location name when selected overlaps the filter's drop down arrow

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#80]
Priority/Severity: Low/Low

Pre-requisites:
Create an event with its location attribute set as follows - 
location: TAUMATAWHAKATANGIHANGAKOAUAUOTAMATEATURIPUKAKAPIKI-MAUNGAHORONUKUPOKAIWHENUAKITNATAHU
(above is the longest place-name in the world :))

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the left-side filters panel, invoke the location combo box and select the newly added location (with the longer location name)

Expected result:
The location name should be displayed properly without any issues

Actual result:
The location name does not gets displayed properly (overlaps the combo box's down arrow) - please refer the screenshot attached.

Screenshot:
<img width="212" alt="Longer location issue-filter" src="https://user-images.githubusercontent.com/120092872/221410288-db876a4d-9bca-4b11-90ef-018ba0022b05.png">

**Comment by Thangaraj-Ideas2it** [comment]
Issue fixed. @WinsCodes please verify

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
