### ISSUE TITLE
Last selected filter option displayed bold even after 'Clear All' is clicked

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#81]
Priority/Severity: Low/Medium

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the left-side filters panel, select any option apart from 'All'
3. Click 'Clear All'
4. Invoke the same filter-combo box again

Expected result:
The related combo box should get reset to it's default option 'All' and all other options should be displayed without any issues

Actual result:
The related combo box should get reset to it's default option 'All' BUT the last selected option gets displayed as bold

**Comment by abarna-visvanathan** [comment]
This issue is delivered on 24th Feb,2023
