### ISSUE TITLE
Loading the Events page does not display the 1st active/upcoming event's tile completely

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#82]
Priority/Severity: Medium/High

Pre-requisites:
Create an event that is in the upcoming days

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/

Expected result:
Page load should result in the 1st active/upcoming event displayed correctly

Actual result:
Page load results in the 1st active/upcoming event displayed partially (please refer the snapshot attached) - please refer the screenshot attached.

Screenshot:
<img width="521" alt="Events page loading-not displaying the 1st active-upcoming event's tile completely" src="https://user-images.githubusercontent.com/120092872/221410875-83d369ae-c3eb-43d8-8aed-61c46d352c73.png">

**Comment by abarna-visvanathan** [comment]
Bug was fixed , Test execution was completed as as part of Sprint 2 and the same was launched successfully on 6th Mar,2023

**Comment by Thangaraj-Ideas2it** [comment]
Modified the code the show the tile on the first load and when filter applied. @WinsCodes  Please verify
