### ISSUE TITLE
Incorrect image displayed when the tag is neither 'PLN Event' nor 'Industry Event'

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#84]
Priority/Severity: Low/Medium

Pre-requisites:
Create an event that has its tag attribute specified as follows: 
tag: "Tree Event" (it should not be PLN Event or Industry Event)

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline, verify the event's tag field

Expected result:
Suitable image should be displayed prefixing the tag field

Actual result:
The image displayed prefixing the tag field is not correct - please refer the screenshot attached

Screenshot:
![Uploading Image incorrect.png…]()

**Comment by abarna-visvanathan** [comment]
This issue is delivered on 24th Feb,2023

**Comment by WinsCodes** [comment]
Reopening defect as it's happening again - please refer the snapshot attached.

Snapshot:
![Broken image for non PLN non Industry tag issue SS](https://user-images.githubusercontent.com/120092872/222780844-d7ccbcf3-5902-48f5-9750-5e62d6213a75.jpg)

**Comment by Thangaraj-Ideas2it** [comment]
Handled the unknown tag scenario. Please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
