### ISSUE TITLE
Setting a filter does not scroll the page automatically

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#85]
Priority/Severity: Medium/Medium

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline, scroll to the top most or bottom most area (so that the filter change to be done in next step will make the page scroll up/down to display the related event)

Expected result:
The page should automatically scroll up/down to display the related event

Actual result:
The page does not automatically scroll up/down to display the related event (the user has to manually scroll to view the related event)

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the issue to scroll automatically. please verify @WinsCodes

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
