### ISSUE TITLE
Unhandled error thrown when a non boolean value is set for the 'dateTBD' attribute 

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#87]
Priority/Severity: Low/Low

Pre-requisites:
Create an event in with its dateTBD attribute specified as follows:
dateTBD: falsee (an extra 'e' added to the expected value 'false' - purposely making it as a non-boolean value)

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/

Expected result:
The events page should load properly without any issues

Actual result:
An unhandled error gets displayed (please refer the snapshot attached)

Snapshot:
![Uploading dateTBD will incorrect value.PNG…]()

**Comment by abarna-visvanathan** [comment]
@WinsCodes , This needs to be checked during PR process as there is a limitation in TINA and this needs to be explored. This issue will not happen as the build will never succeed.
