### ISSUE TITLE
Events module displaying incorrect page title

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#89]
Priority/Severity: High/Medium

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. Verify the page title (displayed on the browser tab)

Expected result:
Suitable name such as 'Events' to be displayed.

Actual result:
The page title is displayed as 'https://events/plnetwork.io' - please refer the snapshot attached.

Snapshot:
<img width="499" alt="Page title issue" src="https://user-images.githubusercontent.com/120092872/221540787-15564009-571e-49e2-b230-f03a9b412ee6.png">

**Comment by Thangaraj-Ideas2it** [comment]
Fixed the above issue. @WinsCodes  please verify

**Comment by WinsCodes** [comment]
Verified that the issue is now resolved.
